services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - .:/app
    env_file:
      - .env

  tests:
    image: golang:1.23-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    command: [ "sh", "-c", "go install github.com/swaggo/swag/cmd/swag@latest && swag init -g internal/server/main.go && go test ./... -cover -v" ]
    env_file:
      - .env